//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selenium.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHacim
    {
        public int Id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string OrtPrice { get; set; }
        public string OrtVolume { get; set; }
    }
}
